kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
resources:
- deployment.yaml
- service.yaml
- internal-service.yaml
secretGenerator:
- name: example-env
  env: .env
images:
- name: docker/example-api
  newName: ACCOUNT.dkr.ecr.us-east-1.amazonaws.com/docker/example-api
  newTag: IMAGE_TAG
